NDefines.NAI.DEVELOPMENT_CAP_BASE = 30
NDefines.NAI.DEVELOPMENT_CAP_MULT = 1.65
NDefines.NAI.GOVERNING_CAPACITY_OVER_PERCENTAGE_TOLERATED = 0.35
--
NDefines.NAI.POWERBALANCE_DISABLE_VERSUS_AI = 1
NDefines.NAI.AI_USES_HISTORICAL_IDEA_GROUPS	= 0
--
NDefines.NAI.ESTATE_MAX_PRIVILEDGES = 4
NDefines.NAI.ESTATE_MAX_WANTED_INFLUENCE = 85.0
NDefines.NAI.ESTATE_MIN_WANTED_CROWNLAND = 20.0
NDefines.NAI.DANGEROUS_ESTATE_INFLUENCE_BUFFER = 6.5
--
NDefines.NAI.AGGRESSIVENESS = 275.0
NDefines.NAI.AGGRESSIVENESS_BONUS_EASY_WAR = 625.0
NDefines.NAI.MISSION_PICK_CHANCE = 50.0
NDefines.NAI.PS_SHORT_TERM_POOL = 250.0
NDefines.NAI.AI_WANT_ACCEPT_CULTURES = 500.0
--
NDefines.NAI.DEFENDER_OF_FAITH_BASE_AI_DESIRE = 0.175
--
NDefines.NAI.REVOLUTION_EMBRACE_MAX_ABSOLUTISM = 40
--
NDefines.NAI.EDICT_VALUE_THRESHOLD = 25
NDefines.NAI.EDICT_VALUE_THRESHOLD_MULTIPLY_DEFICIT = 5.0
NDefines.NAI.EDICT_VALUE_THRESHOLD_MULTIPLY_LOW_INCOME = 1.5
--
NDefines.NAI.AI_TOTAL_DEV_CULTURE_MULTIPLIER = 10