NDefines.NAI.PEACE_DESIRE_AI_PREFS_QUICK_PEACE = 50
NDefines.NAI.FORCE_COMPOSITION_CHANGE_TECH_LEVEL = 16
NDefines.NAI.CONQUEST_INTEREST_DISTANCE = 110
--
NDefines.NAI.ASSIMILATION_INTEREST_AMOUNT_FACTOR = 150
NDefines.NAI.ARMY_DISTANCE_SCORE_IMPACT	= 0.7
NDefines.NAI.BORDER_DISTANCE_SCORE_IMPACT = 7.7
NDefines.NAI.PURSUE_DISTANCE = 85
--
NDefines.NAI.INVADING_MAX_AWAY_RATIO = 1.6
NDefines.NAI.INVADING_BRAVERY = 1.45
NDefines.NAI.INVASION_ARMY_LOOKUP_INTERVAL_ON_FAILURE = 13
--
NDefines.NAI.REGION_PLANNING_HOMELAND_PRIORIZATION = 7.5
NDefines.NAI.MIN_FORCE_LIMIT_SHARE_REGION_ASSIGN = 0.2
NDefines.NAI.MAX_TASKS_NEW_REGION_ASSIGN_ALGORITHM = 100
NDefines.NAI.MAX_ARMIES_NEW_REGION_ASSIGN_ALGORITHM = 80
--
NDefines.NAI.TRANSPORT_FRACTION = 0.25
NDefines.NAI.OVER_FORCELIMIT_AVOIDANCE_FACTOR = 40
NDefines.NAI.ARTILLERY_FRACTION = 0.35
NDefines.NAI.MIN_CAV_PERCENTAGE = 8.0
NDefines.NAI.MAX_CAV_PERCENTAGE = 40
NDefines.NAI.REGIMENTS_PER_GENERAL = 20
NDefines.NAI.ONLY_INFANTRY_MERCS = 0
--
NDefines.NAI.ACCEPTABLE_BALANCE_DEFAULT = 1.375
--
NDefines.NAI.IMPORTANT_PROVINCE_THRESHOLD = 0.03
--
